[workspace]
members = [
    "dev-tool",
    "kpe",
    "layer",
    "rubert",
    "rubert-tokenizer",
    "test-utils",
    "xayn-ai",
    "xayn-ai-ffi",
    "xayn-ai-ffi-c",
    "xayn-ai-ffi-wasm",
]
resolver = "2"

[workspace.metadata]
# minimum supported rust version
msrv = "1.55.0"
