[workspace]
members = [
    "dev-tool",
    "rubert",
    "rubert-tokenizer",
    "test-utils",
    "xayn-ai",
    "xayn-ai-ffi",
    "xayn-ai-ffi-c",
    "xayn-ai-ffi-wasm",
]

[workspace.metadata]
# minimum supported rust version
msrv = "1.51.0"
