[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = "true"

ANDROID_PLATFORM_VERSION = "21"
ANDROID_LIBS_DIR = "bindings/dart/android/src/main/jniLibs"
ANDROID_TARGETS = "arm64-v8a x86_64 x86"

IOS_TARGETS = "aarch64-apple-ios x86_64-apple-ios"

[config]
skip_core_tasks = true
# this avoids cargo make to run these tasks for each crate
default_to_workspace = false

[tasks.default]
dependencies = ["build"]

[tasks.build]
dependencies = ["build-bindgen"]

[tasks.build-mobile.linux]
dependencies = ["build-android"]

[tasks.build-mobile.mac]
dependencies = ["build-android", "build-ios"]

# builds xayn-ai library that can be used to run flutter tests locally
[tasks.build-local]
script = ["""
  cargo build
"""]

[tasks.build-bindgen-dart]
workspace = false
dependencies = ["build-local"]
script = ["""
  cd bindings/dart
  flutter pub run ffigen --config ffigen_common.yaml
  flutter pub run ffigen --config ffigen_mobile.yaml

  # remove unused mobile-only dependency from common
  cd lib/src/common/ffi
  grep --fixed-strings --invert-match "import 'dart:ffi' as ffi;" genesis.dart > genesis
  mv genesis genesis.dart
"""]

[tasks.build-bindgen-wasm]
script = ["""
  wasm-pack build xayn-ai-ffi-wasm --out-dir ../bindings/dart/lib/src/web/ffi --out-name genesis --target web
  # remove glob gitignore: https://rustwasm.github.io/docs/wasm-pack/commands/build.html#footnote-0
  rm bindings/dart/lib/src/web/ffi/.gitignore
"""]

[tasks.build-bindgen]
dependencies = ["build-bindgen-dart", "build-bindgen-wasm"]

[tasks.build-android]
dependencies = ["build-dart-bindgen"]
script = ["""
  cargo ndk $(echo $ANDROID_TARGETS | sed 's/[^ ]* */-t &/g') -p $ANDROID_PLATFORM_VERSION -o $ANDROID_LIBS_DIR build --release
"""]

[tasks.build-ios]
dependencies = ["build-dart-bindgen"]
script = ["""
  cargo lipo --targets $IOS_TARGETS --release
  cp target/universal/release/libxayn_ai_ffi_c.a bindings/dart/ios
"""]


