name: 'build asset artifacts'
description: 'Builds asset artifacts'
inputs:
  dart-ws:
    description: 'The Dart workspace'
    required: true
  wasm-version:
    description: 'The version of the WASM artifacts.'
    required: false
  wasm-out-dir-path:
    description: 'The relative path (wrt the repository root) of the WASM artifacts.'
    required: false
outputs:
  dart-metadata:
    description: "The relative path (wrt the repository root) of the Dart manifest."
    value: ${{ steps.artifact-paths.outputs.dart-metadata }}
  json-metadata:
    description: "The relative path (wrt the repository root) of the JSON manifest."
    value: ${{ steps.artifact-paths.outputs.json-metadata }}
  chunks-dir:
    description: "The relative path (wrt the repository root) of the directory where the chunks of the data assets are stored."
    value: ${{ steps.artifact-paths.outputs.chunks-dir }}
runs:
  using: "composite"
  steps:
    - id: artifact-paths
      shell: bash
      run: |
        echo "::set-output name=dart-metadata::$(echo ${{ inputs.dart-ws }}/lib/src/common/reranker/assets.dart)"
        echo "::set-output name=json-metadata::out/assets_metadata.json"
        echo "::set-output name=chunks-dir::data/chunks"

    - shell: bash
      run: |
        if [ ${{ runner.os }} == "macOS" ]; then
          # installs gsplit
          brew install coreutils
        fi

        bash generate_assets_metadata.sh assets_manifest.json ${{ inputs.wasm-version }} ${{ inputs.wasm-out-dir-path }}

        echo "::group::Dart metadata"
        cat ${{ steps.artifact-paths.outputs.dart-metadata }}
        echo "::endgroup::"
        echo "::group::JSON metadata"
        cat ${{ steps.artifact-paths.outputs.json-metadata }}
        echo "::endgroup::"
