name: 'build asset artifacts'
description: 'Builds asset artifacts'
inputs:
  dart-ws:
    description: 'Dart workspace'
    required: true
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        mkdir -p out
        gomplate -f data/asset_templates/assets.json.tmpl -o out/assets.json
        gomplate -d assets=out/assets.json -f data/asset_templates/assets.dart.tmpl -o ${{ inputs.dart-ws }}/lib/src/common/reranker/assets.dart
        flutter format ${{ inputs.dart-ws }}/lib/src/common/reranker/assets.dart
        echo "::group::asset.dart"
        cat ${{ inputs.dart-ws }}/lib/src/common/reranker/assets.dart
        echo "::endgroup::"
        echo "::group::asset.json"
        cat out/assets.json
        echo "::endgroup::"
