name: 'xayn_ai_ffi_flutter'
version: '4.0.0'
publish_to: none

environment:
  sdk: '>=2.14.4 <3.0.0'
  flutter: '>=2.5.3 <3.0.0'

dependencies:
  flutter:
    sdk: 'flutter'
  xayn_ai_ffi_dart:
    git:
      url: git@github.com:xaynetwork/xayn_ai_release.git
      ref: flutter-dart-setup
      path: dart

dependency_overrides:
  xayn_ai_ffi_dart:
    path: ../dart

dev_dependencies:
  flutter_test:
    sdk: 'flutter'

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: 'com.xayn.xayn_ai_ffi_flutter'
        pluginClass: 'XaynAiFfiFlutterPlugin'
      ios:
        pluginClass: 'XaynAiFfiFlutterPlugin'
