name: xayn_ai_ffi_dart_example
description: Demonstrates how to use the xayn_ai_ffi_dart plugin.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=2.13.1 <3.0.0'
  flutter: '>=2.2.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: '^2.0.2'
  stats: '2.0.0'
  crypto: ^3.0.1

  xayn_ai_ffi_dart:
    # When depending on this package from a real application you should use:
    #   xayn_ai_ffi_dart: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: '^1.11.0'

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your plugin package, add an assets section, like this:
  assets:
    - assets/rubert_v0001/
    - assets/ltr_v0000/
