[package]
name = "dev-tool"
version = "0.1.0"
authors = ["Xayn Engineering <engineering@xaynet.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.40"
structopt = "0.3.21"
xayn-ai = { path="../xayn-ai" }
serde = { version="1.0.126", features=["derive"]}
serde_json = "1.0.64"
base64 = "0.13.0"
