name: 'generate flutter ffi'
description: 'Generates flutter ffi'
inputs:
  dart-ws:
    description: 'The Dart workspace'
    required: true
runs:
  using: "composite"
  steps:
    - shell: bash
      working-directory: ${{ inputs.dart-ws }}
      run: |
        flutter pub run ffigen --config ffigen_common.yaml
        flutter pub run ffigen --config ffigen_mobile.yaml
        grep --fixed-strings --invert-match "import 'dart:ffi' as ffi;" lib/src/common/ffi/genesis.dart > genesis && mv genesis lib/src/common/ffi/genesis.dart
