name: 'wasm-pack'
description: 'Installs wasm-pack'
runs:
  using: "composite"
  steps:
    - shell: bash
      working-directory: ${{ runner.temp }}
      env:
        LINUX_URL: https://github.com/rustwasm/wasm-pack/releases/download/v0.10.0/wasm-pack-v0.10.0-x86_64-unknown-linux-musl.tar.gz
        # `shasum -a 256 wasm-pack`
        LINUX_CHECKSUM: bbd1da4c281346c3a3d612dbac698ed21497d71791ffeceba193b754434aa70b
      run: |
        if [ ${{ runner.os }} == "Linux" ]; then
          URL=${{ env.LINUX_URL }}
          CHECKSUM=${{ env.LINUX_CHECKSUM }}
        else
          echo "::error wasm-pack for ${{ runner.os }} is not supported"
          exit 1
        fi

        wget -q -O - $URL | tar xvzf - --strip-components 1
        echo "$CHECKSUM *wasm-pack" | shasum -c -
        mv wasm-pack $HOME/.cargo/bin/
