/// Warning, this file is autogenerated. Don't modify this manually.

part of 'data_provider.dart';

/// Base assets that are required for both mobile and web.
///
/// The checksum is the sha256 hash of the asset.
/// To calculate the checksum run 'shasum -a 256 vocab.txt'.
final baseAssets = <AssetType, Asset>{
  AssetType.smbertVocab: Asset(
      'smbert_v0000/vocab.txt',
      Checksum(
          'ffb2398810fa977ee39e8a0103b07f9c2614f1f9825df53a2c99e71569e3451c'),
      []),
  AssetType.smbertModel: Asset(
      'smbert_v0000/smbert.onnx',
      Checksum(
          'c07653a3cc568876071de157f0fb8ccc1a302197ddad9ead069a86140e19d913'),
      [
        Fragment(
            'smbert_v0000/smbert.onnx_11MB_00',
            Checksum(
                '7f4d6242ef88ab6daaf1e1fa1f030345c4f4046585cd9576112aa5391f42a000')),
        Fragment(
            'smbert_v0000/smbert.onnx_11MB_01',
            Checksum(
                'bd642e69234c28b3b2c25138f997505195d43a734668ce55de7adebea691ea99')),
        Fragment(
            'smbert_v0000/smbert.onnx_11MB_02',
            Checksum(
                '6987dc3baddff7b742d7a481209b2a4d30097abf911fa29d50bc271dec121008')),
        Fragment(
            'smbert_v0000/smbert.onnx_11MB_03',
            Checksum(
                '510ff0115aef91497fc5ef8ffcfd4c7646644d63ddc0e0635d765cf8f19b8b36')),
        Fragment(
            'smbert_v0000/smbert.onnx_11MB_04',
            Checksum(
                '52e75ac8310bead0817a4948c126d2c2105a2213ec72d4f6864fad15d07d3491')),
      ]),
  AssetType.qambertVocab: Asset(
      'qambert_v0001/vocab.txt',
      Checksum(
          'ffb2398810fa977ee39e8a0103b07f9c2614f1f9825df53a2c99e71569e3451c'),
      []),
  AssetType.qambertModel: Asset(
      'qambert_v0001/qambert.onnx',
      Checksum(
          '030e7d68cc82f59640c6b989f145d6eaa7609c8615bd6ae9e7890e1a68be5b71'),
      [
        Fragment(
            'qambert_v0001/qambert.onnx_11MB_00',
            Checksum(
                '864c75b3132c6282ff2e266ec0e51972371fae60b1678fcb90408e92eb06dfb5')),
        Fragment(
            'qambert_v0001/qambert.onnx_11MB_01',
            Checksum(
                '36d3e3162e60fefd563e7a857a74d03755ed899dc79369f3083fa5ca33c9fed5')),
        Fragment(
            'qambert_v0001/qambert.onnx_11MB_02',
            Checksum(
                '7db90e4fe94690593115032d2b1a30b7b76a2a6b5481cabcc7ffab6b972a76ce')),
        Fragment(
            'qambert_v0001/qambert.onnx_11MB_03',
            Checksum(
                'b0c84da6e10a8ae5c0a1470e5144a4ab5dd142342c25d12968e76f72fe17c32f')),
        Fragment(
            'qambert_v0001/qambert.onnx_11MB_04',
            Checksum(
                '510e9cf989dfc50fe64348d715a543006e04f9e39d75e9ba636e139137f29ac5')),
      ]),
  AssetType.ltrModel: Asset(
      'ltr_v0000/ltr.binparams',
      Checksum(
          'f36a874ba26ea154a02070180cfcabaf191f654ecff5bb94a8472d2881d4c062'),
      []),
};

enum AssetType {
  smbertVocab,
  smbertModel,
  qambertVocab,
  qambertModel,
  ltrModel,
  wasmModule,
  wasmScript,
  webWorkerScript,
}
