/// Warning, this file is autogenerated. Don't modify this manually.

part of 'data_provider.dart';

final _wasmMultithreaded = <common.AssetType, common.Asset>{
  common.AssetType.wasmModule: common.Asset(
      'wasm_bindings/genesis_bg.wasm',
      common.Checksum(
          '42182c72f2f26bee12bf9d31f31ac48291341b832821daff4de8a6400c1fa723'),
      []),
  common.AssetType.wasmScript: common.Asset(
      'wasm_bindings/genesis.js',
      common.Checksum(
          '4f2a405bbafb4dc3ae3ca7679737320351e384d25efdb8f4156c7bf66d9def71'),
      []),
};

/// Returns the most suitable wasm assets for the given features.
Map<common.AssetType, common.Asset> getWasmAssets(
    Set<common.WebFeature> features) {
  if (features.containsAll(_multithreaded)) {
    return _wasmMultithreaded;
  }
  throw UnsupportedError('No suitable WASM assets are available');
}
