[package]
name = "xayn-ai-ffi-wasm"
version = "0.1.0"
authors = ["Xayn Engineering <engineering@xaynet.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console_error_panic_hook = "0.1.6"
getrandom = { version = "0.2.3", features = ["js"] }
js-sys = "0.3.51"
serde = { version = "1.0.126", features = ["derive"] }
serde_repr = "0.1.6"
wasm-bindgen = { version = "0.2.74", features = ["serde-serialize"] }
xayn-ai = { path = "../xayn-ai" }
xayn-ai-ffi = { path = "../xayn-ai-ffi" }

[dev-dependencies]
itertools = "0.10.0"
wasm-bindgen-test = "0.3.24"

[lib]
crate-type = ["cdylib"]

[package.metadata.wasm-pack.profile.profiling]
# -g is required to keep the original function names
wasm-opt = ['-O', '-g']

[features]
default = ["browser"]
browser =[]
node = []
