[package]
name = "xayn-ai-ffi-wasm"
version = "0.1.0"
authors = ["Xayn Engineering <engineering@xaynet.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
js-sys = "0.3.50"
getrandom = { version = "0.2.2", features = ["js"] }
serde = { version = "1.0.125", features = ["derive"] }
wasm-bindgen = { version = "0.2.73", features = ["serde-serialize"] }
xayn-ai = { path = "../xayn-ai" }

[dev-dependencies]
wasm-bindgen-test = "0.3.23"

[lib]
crate-type = ["cdylib"]
[package.metadata.wasm-pack.profile.profiling]
wasm-opt = ['-O', '-g']
