name: xayn_ai_ffi_dart
version: 0.1.0
author: Xayn Engineering <engineering@xaynet.dev>

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0 <3.0.0"

dependencies:
  ffi: ^1.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  ffigen: ^2.4.0
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0

ffigen:
  name: 'XaynAi'
  description: 'Bindings to the xayn-ai-ffi-c library.'
  output: 'lib/xayn_ai_ffi.dart'
  headers:
    entry-points:
      - '../../xayn-ai-ffi-c/xayn_ai.h'
  compiler-opts-automatic:
    macos:
      include-c-standard-library: false
  array-workaround: true
