name: xayn_ai_ffi_dart
version: 0.1.0
author: Xayn Engineering <engineering@xaynet.dev>

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0 <3.0.0"

dependencies:
  ffi: ^1.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  effective_dart: ^1.3.1
  ffigen: ^2.4.0
  flutter_test:
    sdk: flutter

ffigen:
  name: 'XaynAi'
  description: 'Bindings to the xayn-ai-ffi-c library.'
  output: 'lib/xayn_ai_ffi.dart'
  headers:
    entry-points:
      - '../../xayn-ai-ffi-c/xayn_ai.h'
  compiler-opts-automatic:
    macos:
      include-c-standard-library: false
  array-workaround: true
  preamble: |
    // ignore_for_file: avoid_private_typedef_functions
    // ignore_for_file: camel_case_types
    // ignore_for_file: constant_identifier_names
    // ignore_for_file: lines_longer_than_80_chars
    // ignore_for_file: non_constant_identifier_names
    // ignore_for_file: public_member_api_docs
    // ignore_for_file: unused_element
    // ignore_for_file: unused_field
