name: 'xayn_ai_ffi_dart'
version: '1.0.0'
author: 'Xayn Engineering <engineering@xaynet.dev>'

environment:
  sdk: '>=2.13.1 <3.0.0'
  flutter: '>=2.2.1 <3.0.0'

dependencies:
  async: '^2.6.1'
  ffi: '^1.1.2'
  flutter:
    sdk: 'flutter'
  js: '^0.6.3'
  json_annotation: ^4.0.1
  meta: '^1.3.0'
  hex: '^0.2.0'


dev_dependencies:
  build_runner: ^2.0.4
  json_serializable: ^4.1.3
  ffigen: '^3.0.0'
  flutter_test:
    sdk: 'flutter'
  pedantic: '^1.11.0'

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.xayn.xayn_ai_ffi_dart
        pluginClass: XaynAiFfiDartPlugin
      ios:
        pluginClass: XaynAiFfiDartPlugin
