name: 'xayn_ai_ffi_dart'
version: '0.1.0'
author: 'Xayn Engineering <engineering@xaynet.dev>'

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0 <3.0.0'

dependencies:
  async: '^2.5.0'
  ffi: '^1.0.0'
  flutter:
    sdk: 'flutter'
  js: '^0.6.3'

dev_dependencies:
  ffigen: '^2.4.2'
  flutter_test:
    sdk: 'flutter'
  pedantic: '^1.11.0'

ffigen:
  name: 'XaynAiFfi'
  description: 'Bindings to the xayn-ai-ffi-c library.'
  output: 'lib/src/mobile/ffi/genesis.dart'
  headers:
    entry-points:
      - '../../xayn-ai-ffi-c/ffi.h'
    include-directives:
      - '../../xayn-ai-ffi-c/ffi.h'
  compiler-opts-automatic:
    macos:
      include-c-standard-library: false

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.xayn.xayn_ai_ffi_dart
        pluginClass: XaynAiFfiDartPlugin
      ios:
        pluginClass: XaynAiFfiDartPlugin

  # To add assets to your plugin package, add an assets section, like this:
  assets:
    - assets/rubert_v0001/

