name: xayn_ai_ffi_dart
description: A starting point for Dart libraries or applications.
version: '4.0.0'

environment:
  sdk: '>=2.14.4 <3.0.0'

dependencies:
  async: '^2.8.1'
  ffi: '^1.1.2'
  js: '^0.6.3'
  json_annotation: '^4.1.0'
  meta: '^1.7.0'
  hex: '^0.2.0'

dev_dependencies:
  build_runner: '^2.1.2'
  json_serializable: '^5.0.2'
  ffigen: '^4.0.0'
  pedantic: '^1.11.1'
  # lints: ^1.0.0
  # test: ^1.16.0
