/* Generated with cbindgen:0.18.0 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdint.h>

#import <Flutter/Flutter.h>

@interface XaynAiPlugin : NSObject<FlutterPlugin>
@end

typedef struct CXaynAi CXaynAi;

/**
 * Creates and initializes the Xayn AI.
 *
 * # Errors
 * Aborts and returns a null pointer if:
 * - The vocab or model paths are invalid.
 * - The batch or token sizes are invalid.
 *
 * An utf8 encoded, null-terminated message will be written to a valid error pointer.
 *
 * # Safety
 * The behavior is undefined if:
 * - A non-null vocab or model path doesn't point to an aligned, contiguous area of memory with a
 * terminating null byte.
 * - A non-null error doesn't point to an aligned, contiguous area of memory with at least error
 * size bytes.
 */
struct CXaynAi *xaynai_new(const uint8_t *vocab,
                           const uint8_t *model,
                           uint32_t batch_size,
                           uint32_t token_size,
                           float shift_factor,
                           float threshold,
                           uint8_t *error,
                           uint32_t error_size);

/**
 * Reranks the documents with the Xayn AI.
 *
 * Each document is represented as an id, a snippet and a rank. The reranked order is written to
 * the ranks array.
 *
 * # Errors
 * Aborts without changing the ranks if:
 * - The xaynai is null.
 * - The ids, snippets or ranks are invalid.
 * - The document size is zero.
 *
 * An utf8 encoded, null-terminated message will be written to a valid error pointer.
 *
 * # Safety
 * The behavior is undefined if:
 * - A non-null xaynai doesn't point to memory allocated by [`xaynai_new()`].
 * - A non-null ids or snippets array doesn't point to an aligned, contiguous area of memory with
 * at least doc size pointers.
 * - A non-null ranks array doesn't point to an aligned, contiguous area of memory with at least
 * doc size integers.
 * - A non-null id or snippet doesn't point to an aligned, contiguous area of memory with a
 * terminating null byte.
 * - A non-null error doesn't point to an aligned, contiguous area of memory with at least error
 * size bytes.
 */
void xaynai_rerank(const struct CXaynAi *xaynai,
                   const uint8_t *const *ids,
                   const uint8_t *const *snippets,
                   uint32_t *ranks,
                   uint32_t doc_size,
                   uint8_t *error,
                   uint32_t error_size);

/**
 * Frees the memory of the Xayn AI.
 *
 * # Safety
 * The behavior is undefined if:
 * - A non-null xaynai doesn't point to memory allocated by [`xaynai_new()`].
 * - A non-null xaynai is freed more than once.
 */
void xaynai_drop(struct CXaynAi *xaynai);

/**
 * This function does nothing.
 *
 * Calling this prevents Swift to drop the library.
 */
void dummy_function(void);
