/* Generated with cbindgen:0.18.0 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdint.h>
#import <Flutter/Flutter.h>

@interface XaynAiPlugin : NSObject<FlutterPlugin>
@end


typedef struct CXaynAi CXaynAi;

struct CXaynAi *xaynai_new(const uint8_t *vocab,
                           const uint8_t *model,
                           uint32_t batch_size,
                           uint32_t token_size,
                           float shift_factor,
                           float threshold,
                           uint8_t *error,
                           uint32_t error_size);

void xaynai_rerank(const struct CXaynAi *xaynai,
                   const uint8_t *const *ids,
                   const uint8_t *const *snippets,
                   uint32_t *ranks,
                   uint32_t doc_size,
                   uint8_t *error,
                   uint32_t error_size);

/**
 * Frees the memory of the Xayn AI.
 *
 * # Safety
 * The method must be called only once on a pointer to avoid undefined behavior on double-frees.
 */
void xaynai_drop(struct CXaynAi *xaynai);

/**
 * This function does nothing.
 *
 * It is only needed to make a dummy call to the library in the swift code to prevent dropping it.
 */
void dummy_function(void);
