/* Generated with cbindgen:0.18.0 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#import <Flutter/Flutter.h>

@interface XaynAiPlugin : NSObject<FlutterPlugin>
@end

