name: 'copy ffi header files'
description: 'Copies ffi header files'
inputs:
  working-directory:
    description: 'The working directory'
    required: true
  dart-ws:
    description: 'The Dart workspace'
    required: true
  flutter-ws:
    description: 'The Flutter workspace'
    required: true
runs:
  using: "composite"
  steps:
    - shell: bash
      working-directory: ${{ inputs.working-directory }}
      # this might need some changes
      run: |
        cp flutter/ios/Classes/XaynAiFfiCommon.h ${{ inputs.flutter-ws }}/ios/Classes
        cp flutter/ios/Classes/XaynAiFfiDart.h ${{ inputs.flutter-ws }}/ios/Classes
        cp dart/lib/src/common/ffi/genesis.dart ${{ inputs.dart-ws }}/lib/src/common/ffi
        cp dart/lib/src/mobile/ffi/genesis.dart ${{ inputs.dart-ws }}/lib/src/mobile/ffi
        find dart/lib/ -type f -regex ".*\.g\.dart" -exec cp --parents '{}' ${{ inputs.dart-ws }}/ \;
