name: 'copy ffi header files'
description: 'Copies ffi header files'
inputs:
  working-directory:
    description: 'The working directory'
    required: true
  dart-ws:
    description: 'The Dart workspace'
    required: true
runs:
  using: "composite"
  steps:
    - shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        cp ios/Classes/XaynAiFfiCommon.h ${{ inputs.dart-ws }}/ios/Classes
        cp ios/Classes/XaynAiFfiDart.h ${{ inputs.dart-ws }}/ios/Classes
        cp lib/src/common/ffi/genesis.dart ${{ inputs.dart-ws }}/lib/src/common/ffi
        cp lib/src/mobile/ffi/genesis.dart ${{ inputs.dart-ws }}/lib/src/mobile/ffi
        find lib/ -type f -regex ".*\.g\.dart" -exec cp --parents '{}' ${{ inputs.dart-ws }}/ \;
