[package]
name = "xayn-ai-ffi-c"
version = "0.1.0"
authors = ["Xayn Engineering <engineering@xaynet.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ffi-support = "0.4.2"
rubert = { path = "../rubert" }
xayn-ai = { path = "../xayn-ai" }

[build-dependencies]
cbindgen = "0.18.0"

[lib]
crate-type = ["staticlib", "cdylib"]
