name: Audit for Security Vulnerabilities (master)

on:
  schedule:
    - cron: '00 08 * * mon-fri'

jobs:
  audit:
    name: Rust Audit
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4
        with:
          ref: master

      - name: Run cargo-audit
        id: cargo-audit
        run: cargo audit --deny warnings

      - name: Notify on Slack
        uses: 8398a7/action-slack@dcc8c8e9dd8802e21a712dc0c003db97b42efe43 # v3.9.1
        if: ${{ failure() }}
        with:
          status: custom
          fields: workflow,job,repo
          custom_payload: |
            {
              username: 'GitHub Actions',
              icon_emoji: ':octocat:',
              attachments: [{
                color: '${{ steps.cargo-audit.outcome }}' === 'success' ? 'good' : '${{ steps.cargo-audit.outcome }}' === 'failure' ? 'danger' : 'warning',
                text: `${process.env.AS_WORKFLOW}\nRepository: ${process.env.AS_REPO}\nRef: master :warning:`,
              }]
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
