name: Audit for Security Vulnerabilities (master)

on:
  schedule:
    - cron: '00 08 * * mon-fri'

permissions:
  contents: read

jobs:
  audit:
    name: Rust Audit
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4
        with:
          ref: master

      - name: Run cargo-audit
        id: cargo-audit
        continue-on-error: true
        run: |
          OUTCOME=0
          echo 'CARGO_AUDIT<<EOF' >> $GITHUB_ENV
          cargo audit --deny warnings -q 2>&1 >> $GITHUB_ENV || OUTCOME=1
          echo 'EOF' >> $GITHUB_ENV
          exit $OUTCOME

      - name: Notify on Slack
        uses: 8398a7/action-slack@dcc8c8e9dd8802e21a712dc0c003db97b42efe43 # v3.9.1
        if: steps.cargo-audit.outcome != 'success'
        with:
          status: custom
          fields: workflow, repo
          custom_payload: |
            {
              "text": ":package::mag:cargo audit",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": `Workflow: ${process.env.AS_WORKFLOW}\nRepository: ${process.env.AS_REPO}\nRef: \`master\``
                  }
                },
              ],
              "attachments": [{
                "color": 'danger'
                "text": `\`\`\`${{ env.CARGO_AUDIT }}\`\`\``,
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
