name: Audit for Security Vulnerabilities (master)

on:
  schedule:
    - cron: '00 08 * * mon-fri'

permissions:
  contents: read

jobs:
  audit:
    name: Rust Audit
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97 # v2.3.4
        with:
          ref: master

      - name: Run cargo-audit
        id: cargo-audit
        continue-on-error: true
        run: |
          OUTCOME=0
          echo 'CARGO_AUDIT<<EOF' >> $GITHUB_ENV
          (((((cargo audit --deny warnings -q 2>&1; echo $? >&3) | sed 's/`/\\`/g' >&4) 3>&1) | (read xs; exit $xs)) 4>&1) >> $GITHUB_ENV || OUTCOME=1
          echo 'EOF' >> $GITHUB_ENV
          exit $OUTCOME

      - name: Notify on Slack
        uses: 8398a7/action-slack@c84a35cfa82a01f3733a3cbf5d5260123e55c2f9 # v3.9.2
        if: steps.cargo-audit.outcome != 'success'
        with:
          status: custom
          fields: workflow, repo
          custom_payload: |
            {
              "text": ":package::mag:cargo audit",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": `Workflow: ${process.env.AS_WORKFLOW}\nRepository: ${process.env.AS_REPO}\nRef: \`master\``
                  }
                },
              ],
              "attachments": [{
                "color": "danger",
                "text": `\`\`\`${{ env.CARGO_AUDIT }}\`\`\``,
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
