name: Audit for Security Vulnerabilities (master)

on:
  schedule:
    - cron: '00 08 * * mon-fri'

jobs:
  audit:
    name: Rust Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Run rust-audit
        id: rust-audit
        run: |
          cargo audit --deny warnings

      - name: Notify on Slack
        uses: 8398a7/action-slack@v3
        if: ${{ failure() }}
        with:
          status: custom
          fields: workflow,job,repo
          custom_payload: |
            {
              username: 'GitHub Actions',
              icon_emoji: ':octocat:',
              attachments: [{
                color: '${{ steps.rust-audit.outcome }}' === 'success' ? 'good' : '${{ steps.rust-audit.outcome }}' === 'failure' ? 'danger' : 'warning',
                text: `${process.env.AS_WORKFLOW}\nRepository: ${process.env.AS_REPO}\nRef: master :warning:`,
              }]
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
