# You can find more information about the design decisions here:
# https://github.com/xaynetwork/xayn_ai/pull/21

name: Dev CI

on:
  push:
    branches-ignore:
      # we push on release only from staging and release represent
      # a snapshot of staging in a given point in time
      - 'master'
      - 'release'
      - '_bors_staging-squash-merge.tmp'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  RUST_STABLE: 1.51
  RUST_NIGHTLY: nightly-2021-05-10
  CARGO_NDK: 2.4.1
  ANDROID_PLATFORM_VERSION: 21
  # cmd: `shasum -a 256 cross`
  CROSS_CHECKSUM: 18a3599273773a7d1e333b413751f0adc1a83ec8045d060fee4f0639bd6baaf0
  # On targets like `*-linux-android*` and `wasm32-unknown-unknown`, reading the model
  # takes a considerable amount of time if it is compiled with the default opt-level
  # for tests. Therefore, we compile them with a higher opt-level to run them faster.
  OPT_TESTS_RUSTFLAGS: '-C opt-level=3 -C debug-assertions=yes -D warnings'
  FLUTTER_VERSION: '2.5.3'
  DART_WORKSPACE: ${{ github.workspace }}/bindings/dart
  CARGO_INCREMENTAL: 0

jobs:
  cargo-registry-cache:
    # we use the latest stable rustc + cargo version that is already installed on the image
    # https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md#rust-tools
    name: cargo-registry-cache
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    outputs:
      cache-key: ${{ steps.cache-key.outputs.key }}
      cache-date: ${{ steps.get-date.outputs.date }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0

      # We want to create a new cache after a week. Otherwise, the cache will
      # take up too much space by caching old dependencies
      - name: Generate Year + ISO week number key
        id: get-date
        shell: bash
        run: echo "::set-output name=date::$(/bin/date -u "+%Y-%V")"

      - name: Generate cargo registry cache key
        id: cache-key
        shell: bash
        run: echo "::set-output name=key::$(echo ${{ runner.os }}-${{ github.job }}-${{ steps.get-date.outputs.date }}-${{ hashFiles('**/Cargo.lock') }})"

      - name: Restore cargo registry ${{ steps.cache-key.outputs.key }} cache
        uses: actions/cache@c64c572235d810460d0d6876e9c705ad5002b353 # v2.1.6
        with:
          path: |
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git/db
          key: ${{ steps.cache-key.outputs.key }}
          restore-keys: ${{ runner.os }}-${{ github.job }}-${{ steps.get-date.outputs.date }}-

      - name: Fetch dependencies
        run: cargo fetch

  cargo-format:
    name: cargo-format
    needs: cargo-registry-cache
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0

      - name: Install ${{ env.RUST_NIGHTLY }} toolchain
        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1.0.7
        with:
          profile: minimal
          toolchain: ${{ env.RUST_NIGHTLY }}
          components: rustfmt
          default: true

      - name: Use cached cargo registry
        uses: actions/cache@c64c572235d810460d0d6876e9c705ad5002b353 # v2.1.6
        with:
          path: |
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git/db
          key: ${{ needs.cargo-registry-cache.outputs.cache-key }}

      # cargo fmt does not create any artifacts, therefore we don't need to cache the target folder
      - name: cargo fmt
        run: cargo fmt --all -- --check

  cargo-sort:
    name: cargo-sort
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0

      - name: Install cargo-sort
        uses: ./.ci/install-cargo-sort

      - name: cargo sort
        run: cargo sort --grouped --workspace --check

  cargo-check:
    name: cargo-check
    needs: cargo-registry-cache
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    steps:
      - name: Checkout repository
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0

      - name: Install ${{ env.RUST_STABLE }} toolchain
        id: rust-toolchain
        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1.0.7
        with:
          profile: minimal
          toolchain: ${{ env.RUST_STABLE }}
          default: true

      - name: Use cached cargo registry
        uses: actions/cache@c64c572235d810460d0d6876e9c705ad5002b353 # v2.1.6
        with:
          path: |
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git/db
          key: ${{ needs.cargo-registry-cache.outputs.cache-key }}

      - name: Cache build artifacts
        uses: actions/cache@c64c572235d810460d0d6876e9c705ad5002b353 # v2.1.6
        with:
          path: ${{ github.workspace }}/target
          key: ${{ runner.os }}-${{ steps.rust-toolchain.outputs.rustc }}-${{ github.job }}-${{ needs.cargo-registry-cache.outputs.cache-date }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-${{ steps.rust-toolchain.outputs.rustc }}-${{ github.job }}-${{ needs.cargo-registry-cache.outputs.cache-date }}-

      - name: cargo check
        env:
          RUSTFLAGS: "-D warnings"
        run: |
          cargo check --all-targets
          cargo check --all-targets --all-features

  cargo-clippy:
    name: cargo-clippy
    needs: [cargo-registry-cache, cargo-check]
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    steps:
      - name: Checkout repository
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0

      - name: Install ${{ env.RUST_STABLE }} toolchain
        id: rust-toolchain
        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1.0.7
        with:
          profile: minimal
          toolchain: ${{ env.RUST_STABLE }}
          components: clippy
          default: true

      - name: Use cached cargo registry
        uses: actions/cache@c64c572235d810460d0d6876e9c705ad5002b353 # v2.1.6
        with:
          path: |
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git/db
          key: ${{ needs.cargo-registry-cache.outputs.cache-key }}

      - name: Cache build artifacts
        uses: actions/cache@c64c572235d810460d0d6876e9c705ad5002b353 # v2.1.6
        with:
          path: ${{ github.workspace }}/target
          key: ${{ runner.os }}-${{ steps.rust-toolchain.outputs.rustc }}-${{ github.job }}-${{ needs.cargo-registry-cache.outputs.cache-date }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-${{ steps.rust-toolchain.outputs.rustc }}-${{ github.job }}-${{ needs.cargo-registry-cache.outputs.cache-date }}-

      - name: cargo clippy
        run: |
          cargo clippy --all-targets -- --deny warnings
          cargo clippy --all-targets --all-features -- --deny warnings

  cargo-test:
    name: cargo-test
    needs: [cargo-registry-cache, cargo-check]
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    outputs:
      cache-key: ${{ steps.cache-key.outputs.key }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0

      - name: Install ${{ env.RUST_STABLE }} toolchain
        id: rust-toolchain
        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1.0.7
        with:
          profile: minimal
          toolchain: ${{ env.RUST_STABLE }}
          default: true

      - name: Use cached cargo registry
        uses: actions/cache@c64c572235d810460d0d6876e9c705ad5002b353 # v2.1.6
        with:
          path: |
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git/db
          key: ${{ needs.cargo-registry-cache.outputs.cache-key }}

      - name: Generate build artifacts key
        id: cache-key
        shell: bash
        run: echo "::set-output name=key::$(echo "${{ runner.os }}-${{ steps.rust-toolchain.outputs.rustc }}-${{ github.job }}-${{ needs.cargo-registry-cache.outputs.cache-date }}-${{ hashFiles('**/Cargo.lock') }}")"

      - name: Cache build artifacts
        uses: actions/cache@c64c572235d810460d0d6876e9c705ad5002b353 # v2.1.6
        with:
          path: ${{ github.workspace }}/target
          key: ${{ steps.cache-key.outputs.key }}
          restore-keys: ${{ runner.os }}-${{ steps.rust-toolchain.outputs.rustc }}-${{ github.job }}-${{ needs.cargo-registry-cache.outputs.cache-date }}-

      - name: Download data
        run: sh download_data.sh

      - name: Run tests
        env:
          RUSTFLAGS: "-D warnings"
        run: |
          cargo test --all-targets
          cargo test --all-targets --all-features
          cargo test --all-features --doc

  cargo-tarpaulin:
    name: cargo-tarpaulin
    needs: [cargo-registry-cache, cargo-test]
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0

      - name: Install ${{ env.RUST_STABLE }} toolchain
        id: rust-toolchain
        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1.0.7
        with:
          toolchain: ${{ env.RUST_STABLE }}
          profile: minimal
          default: true

      - name: Use cached cargo registry
        uses: actions/cache@c64c572235d810460d0d6876e9c705ad5002b353 # v2.1.6
        with:
          path: |
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git/db
          key: ${{ needs.cargo-registry-cache.outputs.cache-key }}

      - name: Cache build artifacts
        uses: actions/cache@c64c572235d810460d0d6876e9c705ad5002b353 # v2.1.6
        with:
          path: ${{ github.workspace }}/target
          key: ${{ runner.os }}-${{ steps.rust-toolchain.outputs.rustc }}-${{ github.job }}-${{ needs.cargo-registry-cache.outputs.cache-date }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-${{ steps.rust-toolchain.outputs.rustc }}-${{ github.job }}-${{ needs.cargo-registry-cache.outputs.cache-date }}-

      - name: Download data
        run: sh download_data.sh

      - name: Run cargo-tarpaulin
        uses: actions-rs/tarpaulin@044a1e5bdace8dd2f727b1af63c1d9a1d3572068 # v0.1.3
        with:
          version: '0.16.0'
          args: '-v --all-features --force-clean --lib --ignore-tests --fail-under 70 --workspace --exclude xayn-ai-ffi-wasm --exclude dev-tool --timeout 300'

  build-linux-lib:
    name: build-linux-lib
    needs: [cargo-registry-cache, cargo-test]
    runs-on: ubuntu-20.04
    outputs:
      cache-key: ${{ steps.cache-key.outputs.key }}
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0

      - name: Install ${{ env.RUST_STABLE }} toolchain
        id: rust-toolchain
        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1.0.7
        with:
          profile: minimal
          toolchain: ${{ env.RUST_STABLE }}
          default: true

      - name: Use cached cargo registry
        uses: actions/cache@c64c572235d810460d0d6876e9c705ad5002b353 # v2.1.6
        with:
          path: |
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git/db
          key: ${{ needs.cargo-registry-cache.outputs.cache-key }}

      - name: Restore build artifacts
        uses: actions/cache@c64c572235d810460d0d6876e9c705ad5002b353 # v2.1.6
        with:
          path: ${{ github.workspace }}/target
          key: ${{ needs.cargo-test.outputs.cache-key }}

      - name: Build linux lib
        # We have to use the same RUSTFLAGS that are used in the test
        # job in order to be able to reuse the cache. If we do not do this,
        # the compiler will recompile all the libraries from scratch.
        env:
          RUSTFLAGS: "-D warnings"
        run: cargo build

      - name: Generate lib artifacts key
        id: cache-key
        shell: bash
        run: echo "::set-output name=key::$(echo ${{ github.job }}-x86_64-unknown-linux-gnu-${{ hashFiles('target/debug/libxayn_ai_ffi_c.so', '${{ env.DART_WORKSPACE }}/ios/Classes/XaynAiFfiCommon.h', '${{ env.DART_WORKSPACE }}/ios/Classes/XaynAiFfiDart.h') }})"

      - name: Upload library artifacts
        uses: actions/upload-artifact@27121b0bdffd731efa15d66772be8dc71245d074 # v2.2.4
        with:
          name: ${{ steps.cache-key.outputs.key }}
          retention-days: 1
          if-no-files-found: error
          path: |
            ${{ github.workspace }}/target/debug/libxayn_ai_ffi_c.so
            ${{ env.DART_WORKSPACE }}/ios/Classes/XaynAiFfiCommon.h
            ${{ env.DART_WORKSPACE }}/ios/Classes/XaynAiFfiDart.h

  flutter-format:
    name: flutter-format
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0

      - name: Install flutter
        uses: subosito/flutter-action@4389e6cbc6cb8a4b18c628ff96ff90be0e926aa8 # v1.5.3
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Check dart bindings code formatting
        working-directory: ${{ env.DART_WORKSPACE }}
        run: flutter format --set-exit-if-changed .

  flutter-checks:
    name: flutter-checks
    needs: build-linux-lib
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        cmd: [analyze, test]
    steps:
      - name: Checkout repository
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0

      - name: Install libclang-10-dev
        # required by ffigen
        run: sudo apt-get install libclang-10-dev

      - name: Install gomplate
        uses: ./.ci/install-gomplate

      - name: Install flutter
        uses: subosito/flutter-action@4389e6cbc6cb8a4b18c628ff96ff90be0e926aa8 # v1.5.3
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Download ${{ needs.build-linux-lib.outputs.cache-key }} artifacts
        uses: actions/download-artifact@3be87be14a055c47b01d3bd88f8fe02320a9bb60 # v2.0.10
        with:
          name: ${{ needs.build-linux-lib.outputs.cache-key }}
          path: ${{ runner.temp }}/${{ needs.build-linux-lib.outputs.cache-key }}

      - name: Move C-headers and linux lib
        working-directory: ${{ runner.temp }}/${{ needs.build-linux-lib.outputs.cache-key }}
        run: |
          mv bindings/dart/ios/Classes/XaynAiFfiCommon.h ${{ env.DART_WORKSPACE }}/ios/Classes/XaynAiFfiCommon.h
          mv bindings/dart/ios/Classes/XaynAiFfiDart.h ${{ env.DART_WORKSPACE }}/ios/Classes/XaynAiFfiDart.h
          cp -R target ${{ github.workspace }}

      - name: Download data
        run: sh download_data.sh

      - name: Install flutter dependencies
        working-directory: ${{ env.DART_WORKSPACE }}
        run: flutter pub get

      - name: Generate flutter ffi
        uses: ./.ci/generate-flutter-ffi
        with:
          dart-ws: ${{ env.DART_WORKSPACE }}

      - name: Build asset artifacts
        uses: ./.ci/build-asset-artifacts
        with:
          dart-ws: ${{ env.DART_WORKSPACE }}

      - name: Other Dart code generation
        working-directory: ${{ env.DART_WORKSPACE }}
        run: flutter pub run build_runner build

      - name: ${{ matrix.cmd }} flutter code
        working-directory: ${{ env.DART_WORKSPACE }}
        run: flutter ${{ matrix.cmd }}

  # this is an helper that needs all the real leafs of the workflow.
  # It makes easier notify_staging_failure because we only need to check
  # for this job
  ci-ok:
    name: ci-ok
    needs:
      - cargo-sort
      - flutter-format
      - cargo-tarpaulin
      - flutter-checks
    runs-on: ubuntu-20.04
    steps:
      - run: echo "Helper job"

  notify-staging-failure:
    name: notify-staging-failure
    needs: ci-ok
    # always() allows to run even if ci-ok is not successful
    # we only want this to run on the staging branch
    if: always() && github.ref == 'refs/heads/staging'
    runs-on: ubuntu-20.04
    steps:
      - name: Notify failure
        if: needs.ci-ok.result != 'success'
        uses: 8398a7/action-slack@b17d9de8e9ed64b041e4fac845d6fdb2be6b9b04 # v3.9.2
        with:
          status: custom
          fields: workflow, repo
          custom_payload: |
            {
              attachments: [{
                title: 'Staging CI failed :warning:',
                color: 'danger',
                text: `CI: ${process.env.AS_WORKFLOW}\nRepository: ${process.env.AS_REPO}`,
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
