# You can find more information about the design decisions here:
# https://github.com/xaynetwork/xayn_ai/pull/21

name: Dev CI

on:
  push:
    branches-ignore:
      # we push on release only from staging and release represent
      # a snapshot of staging in a given point in time
      - 'master'
      - 'release'
      - '_bors_staging-squash-merge.tmp'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  call-ci-workflow:
    uses: xaynetwork/xaynai/.githbu/workflows/ci_reuse_wf.yml@46f5c668ebc85ff59a5d3eaf5e0dc49aefa39612
    secrets:
      slack: ${{ secrets.SLACK_WEBHOOK_URL }}

