name: Dev CI

on:
  push:
    branches-ignore:
      # we push on release only from staging and release represent
      # a snapshot of staging in a given point in time
      - 'master'
      - 'release'
      - '_bors*'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:

  dev-ci:
    uses: xaynetwork/xayn_ai/.github/workflows/ci_reusable_wf.yml@26482c656e6a079d3b1dd378ba4d0ca911b5a848

  # this is an helper that needs all the real leafs of the workflow.
  # It makes easier notify_staging_failure because we only need to check
  # for this job
  ci-ok:
    name: ci-ok
    needs: dev-ci
    runs-on: ubuntu-20.04
    steps:
      - run: echo "Helper job"

  notify-staging-failure:
    name: notify-staging-failure
    needs: ci-ok
    # always() allows to run even if ci-ok is not successful
    # we only want this to run on the staging branch
    if: always() && github.ref == 'refs/heads/staging'
    runs-on: ubuntu-20.04
    steps:
      - name: Notify failure
        if: needs.ci-ok.result != 'success'
        uses: 8398a7/action-slack@b17d9de8e9ed64b041e4fac845d6fdb2be6b9b04 # v3.11.0
        with:
          status: custom
          fields: workflow, repo
          custom_payload: |
            {
              attachments: [{
                title: 'Staging CI failed :warning:',
                color: 'danger',
                text: `CI: ${process.env.AS_WORKFLOW}\nRepository: ${process.env.AS_REPO}`,
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
