# You can find more information about the design decisions here:
# https://github.com/xaynetwork/xayn_ai/pull/21

name: Dev CI

on:
  push:
    branches-ignore:
      # we push on release only from staging and release represent
      # a snapshot of staging in a given point in time
      - 'master'
      - 'release'
      - '_bors_staging-squash-merge.tmp'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  call-ci-workflow:
    uses: xaynetwork/jorge_test/.github/workflows/test_ci_wf.yml@e73c9b774477480eda211a816a2eb9b3cc3cdbd4
    secrets:
      slack: ${{ secrets.SLACK_WEBHOOK_URL }}

